Livefyre/streamhub-wall

examples/mediawall/index.php
=> Removed commented out 'crappy' code. Minor formatting examples.

bower.json, package.json
Depends on tag from https://github.com/Livefyre/streamhub-sdk/pull/313
=> (DNM) 20150217 configinitial

bower.json, package.json
=> rc->master

.gitignore, Makefile, bower.json, examples/theme-change/index.html, examples/theme-change/theme-change.js, gulpfile.js, package.json, requirejs.conf.js, src/styles/theme.css, src/wall-component.js, src/wall-header-view.js
Using the streamhub-sdk css theme files to generate a themable css file that can be used with the styler.
=> Supporting the livefyre-theme-styler updates

bower.json, package.json
https://livefyre.atlassian.net/browse/LF-18113
=> LF-18113: Bumping version so customers get streamhub-input update

bower.json, package.json
https://livefyre.atlassian.net/browse/LF-19635
=> LF-19635: Upgrade streamhub input ii

bower.json, package.json, src/wall-component.js, src/wall-header-view.js, tests/spec/wall-component.js
https://livefyre.atlassian.net/browse/LF-20297
#review
=> LF-20297: Add translation support for upload button and content editor modal

src/wall-component.js
https://livefyre.atlassian.net/browse/LF-20072
=> LF-20072: Handle postConfig items from designer in configure

bower.json, package.json
https://livefyre.atlassian.net/browse/LF-20009
https://livefyre.atlassian.net/browse/LF-20069
https://livefyre.atlassian.net/browse/LF-20277
https://livefyre.atlassian.net/browse/LF-20449
=> Updates 3.7.2

bower.json, package.json, src/wall-view.js, tests/spec/wall-view.js
https://livefyre.atlassian.net/browse/LF-18042
=> LF-18042: Fixing odd initial visible problems

README.md, src/styles/theme.css
Wrapped media wall URLs inside the card border.
Wrapped the text on media wall content card correctly.
=> LF-19157, LF-20205

src/wall-view.js, tests/spec/wall-view.js
https://livefyre.atlassian.net/browse/LF-20901
=> LF-20901: Limit round robin columns

bower.json, package.json
https://livefyre.atlassian.net/browse/LF-20205
=> LF-20205: Bump version of SDK

bower.json, package.json
https://livefyre.atlassian.net/browse/LF-20668
https://livefyre.atlassian.net/browse/LF-21183
https://livefyre.atlassian.net/browse/LF-21199
=> LF-20668, LF-21183, LF-21199: Bumping SDK and share

bower.json, package.json
https://livefyre.atlassian.net/browse/LF-19426
=> LF-21199: Bumping version of SDK

Makefile, example.js, examples/auth/auth-demo.js, examples/theme-change/theme-change.js, examples/themes/themes-demo.js, examples/wall-view/wall-view-demo.js, gulpfile.js, package.json, requirejs.conf.js, src/post-buttons.js, src/themes/large.js, src/themes/medium.js, src/themes/small.js, src/wall-component.js, src/wall-header-view.js, src/wall-view.js, tests/jasmine.js, tests/karma.conf.js, tests/lib/function.bind.js, tests/spec/main.js, tests/spec/wall-component.js, tests/spec/wall-header-view.js, tests/spec/wall-view.js, tests/test-in-browser.js, tests/test-in-karma.js, tools/build.conf.js, tools/build_version.js
@ross-pfahler's work for the linter rebased
=> lfeslint is now the hinter

Makefile, bower.json, examples/wall-view/index.html
https://livefyre.atlassian.net/browse/LF-21235
=> LF-21235: Bumping SDK, livefyre-bootstrap, streamhub-share

bower.json, package.json, requirejs.conf.js, src/wall-view.js
https://livefyre.atlassian.net/browse/LF-21155
=> LF-21155 enabling the new multiple images view from sdk

bower.json, package.json
https://livefyre.atlassian.net/browse/LF-19379
=> LF-19379 adding sdk that supports youtube streams

bower.json, package.json
https://livefyre.atlassian.net/browse/LF-22123
#review
=> LF-22123 adding sdk fix to handle missing attr

bower.json, examples/mediawall/index.html, package.json, requirejs.conf.js, src/wall-component.js, tests/spec/wall-component.js
https://livefyre.atlassian.net/browse/LF-22010
=> LF-22010: Adding app-base with translations and emitter

bower.json, package.json
to avoid caching silliness....
=> Patch version bump

bower.json, package.json
https://livefyre.atlassian.net/browse/LF-22537
=> LF-22537: Using new version of app-base

Makefile, bower.json, package.json, src/wall-component.js, tests/spec/wall-component.js
1. Fixing bug where `stylePrefix` was passed incorrectly to the header view
2. Bumping `app-base` for translation and theme fixes
3. Bumping `streamhub-sdk` for translation fixes
=> Bug fixes + translations update

bower.json, package.json
https://livefyre.atlassian.net/browse/LF-22742
=> LF-22742: Bumping SDK version

bower.json, package.json
https://livefyre.atlassian.net/browse/LF-22790
=> LF-22790: Bumping SDK version

bower.json, package.json, src/wall-component.js
https://livefyre.atlassian.net/browse/LF-22790
=> LF-22790: Fixing translations

.gitignore, bower.json, package.json, src/styles/theme.css
=> Fix color issue with featured tag

bower.json, package.json
https://livefyre.atlassian.net/browse/LF-22903
=> LF-22903: Fix twitter link attachment issue

bower.json, package.json
https://livefyre.atlassian.net/browse/LF-22893
=> LF-22893: Adding createdAtUrl to instagram and facebook

bower.json, package.json, src/styles/wall-view.css
https://livefyre.atlassian.net/browse/LF-19381
=> LF-19381 updating sdk version for fycon changes

bower.json, package.json
https://livefyre.atlassian.net/browse/LF-22375
=> LF-22375: Bumping version for youtube video sizing

bower.json, requirejs.conf.js
https://livefyre.atlassian.net/browse/LF-23043
=> LF-23043: Adding weibo content

bower.json, package.json
https://livefyre.atlassian.net/browse/LF-23043
=> LF-23043: Bumping SDK version for Weibo

bower.json, gulpfile.js, package.json
https://livefyre.atlassian.net/browse/LF-23333
=> LF-23333: Bumping SDK and Input

bower.json, package.json
https://livefyre.atlassian.net/browse/LF-23333
=> LF-23333: Bumping SDK version

bower.json, src/themes/large.js, src/themes/medium.js, src/themes/small.js, src/themes/xlarge.js, src/themes/xsmall.js, src/wall-component.js
https://livefyre.atlassian.net/browse/LF-20016: Adding xsmall and xlarge themes
https://livefyre.atlassian.net/browse/LF-23308: Date string translations
=> Updates for coke

bower.json, package.json
https://livefyre.atlassian.net/browse/LF-23333
https://livefyre.atlassian.net/browse/LF-23500
=> Bump SDK version

bower.json, package.json
https://livefyre.atlassian.net/browse/LF-23439
=> LF-23441 adding accessibility stuff via include updates

bower.json, package.json
https://livefyre.atlassian.net/browse/LF-23441
https://livefyre.atlassian.net/browse/LF-23439
=> LF-23439 LF-23441 updating sdk version for share button

bower.json, package.json
https://livefyre.atlassian.net/browse/LF-23439
=> LF-23439 sdk version for button key event

bower.json, package.json, src/wall-component.js
https://livefyre.atlassian.net/browse/LF-23799
=> LF-23799: Adding support for liker and sharer delegation

bower.json, package.json
https://livefyre.atlassian.net/browse/LF-23439
=> LF-23439 keycode events refactor and improvement

bower.json, package.json
DEPENDS on: https://github.com/Livefyre/streamhub-sdk/pull/417/files -- tests will fail until that is merged.
https://jira.corp.adobe.com/browse/FYR-651
=> FYR-651: Fix dup titles

bower.json, package.json, src/wall-component.js, src/wall-view.js
https://jira.corp.adobe.com/browse/FYR-1875
=> FYR-1875: Supporting carousel modal

bower.json, package.json
https://jira.corp.adobe.com/browse/FYR-3134
=> FYR-3134: Bumping SDK

bower.json, package.json, src/wall-component.js, src/wall-view.js
https://jira.corp.adobe.com/browse/FYR-3149
=> FYR-3149: Support config to hide social branding

bower.json, package.json, src/styles/theme.css
https://jira.corp.adobe.com/browse/FYR-3359
=> FYR-3359: Fix theme issue

Jenkinsfile, bower.json, package.json, src/wall-component.js, src/wall-view.js
https://jira.corp.adobe.com/browse/FYR-3227
=> FYR-3227: Moving collection processing to app-base

bower.json, package.json
https://jira.corp.adobe.com/browse/FYR-4383
=> FYR-4383: Bumping SDK version

bower.json, package.json, src/styles/theme.css
https://jira.corp.adobe.com/browse/FYR-4698
=> FYR-4698: linkColor is not being applied

bower.json, package.json, src/styles/theme.css
https://jira.corp.adobe.com/browse/FYR-4698
=> Master -> RC

bower.json, package.json
https://jira.corp.adobe.com/browse/FYR-5235
=> FYR-5235: Bumping SDK version

bower.json, package.json, src/wall-component.js, src/wall-view.js
https://jira.corp.adobe.com/browse/FYR-5684
=> FYR-5684: Adding DNT support

bower.json, package.json, src/wall-component.js
https://jira.corp.adobe.com/browse/FYR-5822
=> FYR-5822: Bumping SDK

bower.json, package.json
https://jira.corp.adobe.com/browse/FYR-7497
=> FYR-7497: Bumping SDK

bower.json, package.json
https://jira.corp.adobe.com/browse/FYR-8012
=> FYR-8012: Bumping SDK version

bower.json, package.json
https://jira.corp.adobe.com/browse/FYR-8094
=> FYR-8094: Bumping SDK

bower.json, package.json
Reverts Livefyre/streamhub-wall#406
=> Revert "Master -> RC"

bower.json, package.json
=> FYR-11820: Update bower.json
